### ISSUE TITLE
Taxi Presentation

### ISSUE THREAD

**Issue by rmglazner** [JestonBlu/Neighbor-Works#17] opened 2017-04-25 01:47 UTC
I have just finished recording the  first version of the taxi presentation. Right now it is 6 minutes and 23 seconds long. The video was too large to upload to Github, so I am uploading it to Google Drive where I will then share it with your accounts. I have also shared the Google slides with you, here is the link to that again:

https://docs.google.com/a/tamu.edu/presentation/d/1skXgxYvMRobi20H31xHaBal5kLPRN9Ni310mq-0ZZy8/edit?usp=sharing

I am really not sure what to discuss with the full and reduced models. I tried my best for this practice version, but you will probably notice I struggled. I am sure there is a lot more that I can talk about to get the presentation closer to 10 minutes, but at this point I do not know what exactly that would be.

Please feel free to add information to the presentation and to provide any feedback from the video I am sharing with you all! It is uploading now, and you should be able to view it in about 10 minutes.

@JestonBlu @NancyDrew484 @nitroys

**Comment by rmglazner** [comment] 2017-04-25 01:50
The video was just shared with you. Here is the link too: https://drive.google.com/open?id=0B2Ln8d5D1JADSGpDYnFYM0pJcGc

**Comment by JestonBlu** [comment] 2017-04-25 02:31
Thanks Rachel, i took a look at the slides and Ill add some more talking points tomorrow.  I think we should show the student plots for at least the reduced model and we can make a few statements about overall fit.  I know we cant list the model estimates because there are so many, but we can say what was significant overall.

I would also include the plots that shows which hours are significant, because you can make a statement that people tend to tip more in the morning and less in the afternoon.

**Comment by nitroys** [comment] 2017-04-25 14:05
I added a few things to the slides too. I'll take a look at the video before we meet tonight. Can we also discuss the report tonight and divvy up the portions that need to be filled in there?

**Comment by rmglazner** [comment] 2017-04-25 14:32
Thank you for the edits! After our meeting tonight, I can re-record and send a new version. That gives everyone time tomorrow to view a second version of the video, and suggest any last-minute changes so I can then record a third and final video (if necessary).

I agree that discussion of task division for the remainder of the report is also a good idea during tonight's meeting.

**Comment by JestonBlu** [comment] 2017-04-25 17:11
I have added a few more slides and inserted comments in several others. I havent watched the video yet so Im not sure if you covered these items already, but i thought I would add them as potential talking points or answers to potential questions we might get after the presentation.

**Comment by rmglazner** [comment] 2017-04-25 17:13
Thank you, I read through your comments and most of them I did not directly address in the video, so I will be sure to include them in my next recording!

**Comment by rmglazner** [comment] 2017-04-26 02:07
Here is the link to the newest presentation:https://drive.google.com/a/tamu.edu/file/d/0B2Ln8d5D1JADelVVdFp1a0ZhMDg/view?usp=sharing

I have also shared the video with you from Google Drive. The new video length is 10:54.

Please let me know if you think there are changes that should be made, and I can record again if needed! If you think this version is good, I can send it to the professor.

**Comment by nitroys** [comment] 2017-04-26 20:07
Overall I think it's very good! I have some minor changes, but they aren't absolutely necessary if everyone else thinks it's fine.

I would just maybe mention how tip percent was calculated and include a transition sentence between talking about fixed effects vs random effects. I also noticed a typo in the concluding slide that I have now fixed.

Like I said, these are a little nitpicky and might not require a full retaping. Overall I think it looks good and your words are clear and you aren't talking too fast :)

**Comment by rmglazner** [comment] 2017-04-26 20:12
Great, thank you for the feedback! I have no problem with recording again as it only takes 10 minutes, but I will wait for any comments from Anne and Joseph before I do that :) By tip percent, do you mean you would like me to state that the percent of tip was calculated relative to the total fare for its respective observation? Also, what type of transition sentence do you think would work best between fixed and random effects (and which slide number would that be)?

Thank you again, let's get voted number one presentation! :)

**Comment by nitroys** [comment] 2017-04-26 21:05
Yeah, exactly, for the tip percent. I just don't know if the name is clear enough. And maybe something like, "now that we've looked at the fixed effects, let's turn to the results for the random effects." Or whatever is a more natural wording for you! That'll be right after slide 11/before slide 12.

**Comment by rmglazner** [comment] 2017-04-26 22:03
Okay, thank you! Is the presentation document also okay to send to the professor with the video? I was going to download it as a PowerPoint and send it to her in an email if the group is okay with that.

**Comment by JestonBlu** [comment] 2017-04-26 22:12
I think you did very well. If you want to give it another try go ahead, but I think its good enough.

**Comment by JestonBlu** [comment] 2017-04-26 22:13
I would say the slides are good to send with the video.

**Comment by rmglazner** [comment] 2017-04-26 22:13
Okay, thank you! I just realized we did not include a slide with the formal equations for our full and reduced models. Should we include that?

**Comment by JestonBlu** [comment] 2017-04-26 22:15
I need to make a few adjustments to the equation, if you want to add it you can, but i think it might be enough that its in the paper

**Comment by rmglazner** [comment] 2017-04-26 23:07
Okay, I agree. I haven't heard from Anne yet but I am just going to go ahead and record one more version of the video so you all can choose which one to send. I will also send the PowerPoint witch whichever version is best!

**Comment by rmglazner** [comment] 2017-04-26 23:29
I am screen recording soon, so please avoid changing the slides for the next 15 minutes :)

**Comment by JestonBlu** [comment] 2017-04-26 23:46
oops, sorry, just saw this note... im done making edits for now

**Comment by JestonBlu** [comment] 2017-04-26 23:47
nvm, i was making doc edits not slide edits

**Comment by profgeraci** [comment] 2017-04-26 23:52
Hi, guys. Just getting to this today.  I watched the video earlier today and I'm fine with it.  Thanks for recording another one, Rachael.  I wasn't going to mention adding the equations to the presentation, but since Joseph put them in, that's great.   Looks good!

Also, I write a Summary in the Project document, as agreed last night.  Feel free to word-smith it or modify it if you want to.

**Comment by rmglazner** [comment] 2017-04-27 00:08
No worries! I recorded another version that I am uploading to google drive now. Can you all please watch it when I send the link and let me know if it is good to send to her tonight?

I decided not to include the equations because by the time I was recording the third version there was no equation for the reduced model, and also I had already gone over 10 minutes so I did not want to spend too much more time on that than needed if that's okay! I watched all of Tuesday's presentations and the equations seem to be a very minimal part of the presentation, if there at all.

No worries about the edits, Joseph! I had just noticed that your account was viewing the slides right before I was going to record, and I did not want any accidental edits being made as the video was running, but there were no issues!

**Comment by rmglazner** [comment] 2017-04-27 00:10
Here is the link to the new video: https://drive.google.com/a/tamu.edu/file/d/0B2Ln8d5D1JADMEVUeWRleWFWaUE/view?usp=sharing

If you think this one is good, please let me know. It may be a few more minutes that the video needs to be processed before it will play. I also shared it with your Texas A&M accounts, so you should all have access.

Please let me know if there are any issues viewing the video, and if I can go ahead and send the presentation and presentation document to the professor tonight!

**Comment by nitroys** [comment] 2017-04-27 00:47
Looks good to me!! Thanks for recording again!

**Comment by rmglazner** [comment] 2017-04-27 01:05
Great, thank you! If I don't receive objections from the others by 8:30 I am going to send it to the professor! I will copy the group in that email so we all know when it has been sent. I will be in the field for my research tomorrow morning so I want to be sure that I have this worked out tonight. I will attend the class online to answer any questions tomorrow at 12:45!

**Comment by JestonBlu** [comment] 2017-04-27 01:32
Well done Rachel, great job! Lets submit it.

**Comment by profgeraci** [comment] 2017-04-27 01:40
Yes, I'm good with submitting it. Thanks, Rachael.

**Comment by rmglazner** [comment] 2017-04-27 01:45
Thanks! I have emailed her the video and presentation, and you were all copied in the email!

**Comment by rmglazner** [comment] 2017-04-27 01:52
I also posted in the discussion board so that in the rare scenario where she doesn't see the email, she or someone else in the class will be aware that it is there.

**Comment by rmglazner** [comment] 2017-04-27 02:18
She has received our email and the video is good to go!

**Comment by profgeraci** [comment] 2017-04-27 13:12
Great!   Good luck, Rachael.  You did a great job on the video.

**Comment by profgeraci** [comment] 2017-04-27 13:17
Joseph:   Thanks so much for posting the Rmd file for the Equation.  That is a good thing to know.  Do you have to code all those tags and {align} commands, or is there a way to automate that?

**Comment by JestonBlu** [comment] 2017-04-27 15:48
Im no latex expert so Im not sure, but think its pretty much manual. There are latex editors that probably make it easier, but as far as I know there are no special features like that in RStudio which is what I use primarily for R.

**Comment by rmglazner** [comment] 2017-04-27 18:37
Okay, so there were some questions about our data cleaning after our presentation, but the professor didn't seem too convinced by my answers. This should be something we clarify in our report. Basically, I was asked why we included observations with no tips, but did not include observations with tips greater than 100% of the fare. I was honestly not expecting this question, and my response was that the tips greater than 100% skewed the data and misrepresented it, but we considered not giving a tip a type of tip behavior worth including. I also said that the credit card data was more reliable and showed tipping more often. The professor said she was not fully convinced by that explanation. I may have not stated the reasoning correctly, but I was caught off guard from the questions I was preparing for, so sorry if I totally messed that up!

Anyway, that seemed to be the only major thing to address clearly in the report!

**Comment by JestonBlu** [comment] 2017-04-27 18:51
Thanks Rachel.  According the the data documentation, which we should probably include as an appendix in our report, only credit card transactions had tips reported. I think there were technically a few cash observations that reported a tip, but it was extremely rare. I just checked the data and only .02% of cash transactions reported a tip so its virtually non-existent. 

There were only a couple observations that have tip % > 100 so I dont think that really has a bearing on anything given our data size, but I initially excluded them because I was playing with a beta regression which would require all values be between 0 and 1. This is not probably something we want to put in our write up though.  

I would say the real reason we excluded it is because its very rare and not really representative of tipping behavior, while tip amount = 0 occurred about 5% of the time in the data set. There were ~ 30 observations with tipping > 100% out of 120K records and the highest had a tip amount that was 30 times the fare amount.  I think these are good points for removing them from the data set.

I can add some of these points to the data section of the report tonight.

**Comment by rmglazner** [comment] 2017-04-27 18:54
Great, thank you!

**Comment by nitroys** [comment] 2017-04-27 19:13
Yeah I agree with what Joseph says. Thank you though, Rachel, for handling the presentation and the questions!!

**Comment by profgeraci** [comment] 2017-04-27 21:39
Thanks for agreeing to address this in the report, Joseph.  If that's all they had to criticize, I would say that we rocked this.    Great job, Rachael!  

Let me know if there's anything I can do to help.

**Comment by JestonBlu** [comment] 2017-04-28 00:38
Okay I redid the data description section related to reducing the data set. I may have written a little too much because it looks like there is some wasted space in the document.

Can everyone read the document and give it a proof read? Also, is there anything you think we are missing?

**Comment by profgeraci** [comment] 2017-04-28 00:50
I just added a comment in the document for you, Joseph, but mostly it looks good.   I think this does a good job of explaining the data cleanup tasks we performed.

**Comment by rmglazner** [comment] 2017-04-28 01:05
Thanks everyone! I am reading through the document now, and it looks good to me! There is an 8 page report limit, and ours was 9 pages long, so I changed the font size from 11 to 10. If you think that is too small though and have a better way to format the document go for it!

**Comment by profgeraci** [comment] 2017-04-28 01:13
Yes, that looks better, Rachael.  I did a little reformatting on page 3 so that we didn't have an orphan on the top of page 4.  I also changed the Page header to read "Page x".  
I think it's ready to go once we resolve my comment on Page 2.

**Comment by JestonBlu** [comment] 2017-04-28 01:32
How is this? "We also restricted latitudes and longitudes to the areas between Manhattan and JFK International Airport which removed a few trips that occurred outside of the New York area."

**Comment by profgeraci** [comment] 2017-04-28 01:45
Yes.  That's great.  Thanks, Joseph.

**Comment by JestonBlu** [comment] 2017-04-28 01:46
If everyone is good with the report I can send it with all of the supporting files. Let me know and Ill get everything together.

**Comment by profgeraci** [comment] 2017-04-28 01:47
GREEN LIGHT from me!

**Comment by JestonBlu** [comment] 2017-04-28 01:59
FYI I saved the doc as a pdf and it rendered in 8 pages so we are good to go with the length.

**Comment by nitroys** [comment] 2017-04-28 02:06
Works for me too!!

**Comment by JestonBlu** [comment] 2017-04-28 02:10
Alright, im going to submit and copy everyone.

**Comment by JestonBlu** [comment] 2017-04-28 02:18
Okay, its all submitted. I enjoyed working with all of you!

**Comment by nitroys** [comment] 2017-04-28 12:22
Did you also submit via Filex? Because she probably will ask you to do so anyway.

**Comment by JestonBlu** [comment] 2017-04-28 12:30
I did not, but I will now.

**Comment by JestonBlu** [comment] 2017-04-28 12:33
where is the filex link?

**Comment by JestonBlu** [comment] 2017-04-28 12:45
Wait, are we group 3? I think put group 2 on our file

**Comment by JestonBlu** [comment] 2017-04-28 12:59
I cant seem to figure out where the filex link is. I just uploaded 2 files to our main folder. Can someone who knows how to submit them do that for me?  I updated the file names, they are [Group3_Taxi_Analysis.pdf] and [Group 3 - Taxi Analysis.zip]

**Comment by nitroys** [comment] 2017-04-28 13:03
Yep I can do it! And yes, we're group 3, haha.

**Comment by JestonBlu** [comment] 2017-04-28 13:04
Sorry about that, thanks!

**Comment by nitroys** [comment] 2017-04-28 13:21
No worries! I got both files uploaded to Filex. Thanks guys! This was a great semester, and I enjoyed working with you all on these projects :)

**Comment by profgeraci** [comment] 2017-04-28 13:42
Thanks everyone.  I wasn't going to mention that we are group 3 - I figured that Dr. A would figure it out.  8-)   It was great working with all of you this semester.  Good luck to you (and to me next semester teaching "Introduction to Data Science" - AAAAAAAAHHHH).

**Comment by rmglazner** [comment] 2017-04-28 13:51
Thank you for submitting the document, Joseph!

It was great working with all of you, thank you all for making the project as good as it was!

**Comment by JestonBlu** [comment] 2017-04-29 15:04
I was just able to watch our presentation and listed to the questions. I thought you answered them fine. I don't think you really misstated anything. Either way I think it was good to get those questions so we could make our clarifications in the paper. Thanks for recording and being available for the Q&A.

**Comment by rmglazner** [comment] 2017-04-29 18:37
That's good, thank you for letting me know!

**Comment by JestonBlu** [comment] 2017-05-15 12:50
Hey everyone, in the next couple of weeks I will probably be closing this repo and consolidating the analysis. If anyone wants to keep a standalone copy make sure you click the 'download or clone' button on the main page. Enjoy your summer!

**Closed as completed** 2019-01-25 04:51 UTC
